# Generated by Django 3.2.23 on 2023-12-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carousel.carousel')),
            ],
            options={
                'db_table': 'carousel_images',
            },
        ),
    ]
