# Generated by Django 3.2.23 on 2023-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vichar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vichar_images')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
