# Generated by Django 3.2.23 on 2023-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=256)),
                ('site_logo', models.ImageField(upload_to='site_logo')),
                ('site_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
    ]
