# Generated by Django 3.2.23 on 2023-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaner', models.ImageField(upload_to='daan_scaner')),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daan_details',
            },
        ),
    ]
